export const RELAY_ERROR_CODES = {
    AMOUNT_TOO_LOW: 'AMOUNT_TOO_LOW',
    CHAIN_DISABLED: 'CHAIN_DISABLED',
    EXTRA_TXS_NOT_SUPPORTED: 'EXTRA_TXS_NOT_SUPPORTED',
    FORBIDDEN: 'FORBIDDEN',
    INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
    INSUFFICIENT_LIQUIDITY: 'INSUFFICIENT_LIQUIDITY',
    INVALID_ADDRESS: 'INVALID_ADDRESS',
    INVALID_EXTRA_TXS: 'INVALID_EXTRA_TXS',
    INVALID_GAS_LIMIT_FOR_DEPOSIT_SPECIFIED_TXS: 'INVALID_GAS_LIMIT_FOR_DEPOSIT_SPECIFIED_TXS',
    INVALID_INPUT_CURRENCY: 'INVALID_INPUT_CURRENCY',
    INVALID_OUTPUT_CURRENCY: 'INVALID_OUTPUT_CURRENCY',
    INVALID_SLIPPAGE_TOLERANCE: 'INVALID_SLIPPAGE_TOLERANCE',
    NO_SWAP_ROUTES_FOUND: 'NO_SWAP_ROUTES_FOUND',
    NO_INTERNAL_SWAP_ROUTES_FOUND: 'NO_INTERNAL_SWAP_ROUTES_FOUND',
    NO_QUOTES: 'NO_QUOTES',
    ROUTE_TEMPORARILY_RESTRICTED: 'ROUTE_TEMPORARILY_RESTRICTED',
    SANCTIONED_CURRENCY: 'SANCTIONED_CURRENCY',
    SANCTIONED_WALLET_ADDRESS: 'SANCTIONED_WALLET_ADDRESS',
    SWAP_IMPACT_TOO_HIGH: 'SWAP_IMPACT_TOO_HIGH',
    UNAUTHORIZED: 'UNAUTHORIZED',
    UNSUPPORTED_CHAIN: 'UNSUPPORTED_CHAIN',
    UNSUPPORTED_CURRENCY: 'UNSUPPORTED_CURRENCY',
    UNSUPPORTED_EXECUTION_TYPE: 'UNSUPPORTED_EXECUTION_TYPE',
    UNSUPPORTED_ROUTE: 'UNSUPPORTED_ROUTE',
    USER_RECIPIENT_MISMATCH: 'USER_RECIPIENT_MISMATCH',
    DESTINATION_TX_FAILED: 'DESTINATION_TX_FAILED',
    ERC20_ROUTER_ADDRESS_NOT_FOUND: 'ERC20_ROUTER_ADDRESS_NOT_FOUND',
    SWAP_QUOTE_FAILED: 'SWAP_QUOTE_FAILED',
    PERMIT_FAILED: 'PERMIT_FAILED',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
};

export const getRelayErrorMessage = (errorCode, fallbackMessage) => {
    const messages = {
        [RELAY_ERROR_CODES.AMOUNT_TOO_LOW]: 'Amount is too low for this swap. Try a larger amount.',
        [RELAY_ERROR_CODES.CHAIN_DISABLED]: 'This chain is temporarily disabled.',
        [RELAY_ERROR_CODES.EXTRA_TXS_NOT_SUPPORTED]: 'Extra transactions are not supported for this route.',
        [RELAY_ERROR_CODES.FORBIDDEN]: 'This request is not permitted.',
        [RELAY_ERROR_CODES.INSUFFICIENT_FUNDS]: 'Insufficient balance to complete this swap.',
        [RELAY_ERROR_CODES.INSUFFICIENT_LIQUIDITY]: 'Not enough liquidity available. Try a smaller amount or different token.',
        [RELAY_ERROR_CODES.INVALID_ADDRESS]: 'Invalid wallet address.',
        [RELAY_ERROR_CODES.INVALID_EXTRA_TXS]: 'Extra transactions exceed the intended output.',
        [RELAY_ERROR_CODES.INVALID_GAS_LIMIT_FOR_DEPOSIT_SPECIFIED_TXS]: 'Invalid gas limit for deposit-specified transactions.',
        [RELAY_ERROR_CODES.INVALID_INPUT_CURRENCY]: 'Unsupported input token for this route.',
        [RELAY_ERROR_CODES.INVALID_OUTPUT_CURRENCY]: 'Unsupported output token for this route.',
        [RELAY_ERROR_CODES.NO_SWAP_ROUTES_FOUND]: 'No route found for this swap. The token pair may not be supported.',
        [RELAY_ERROR_CODES.NO_INTERNAL_SWAP_ROUTES_FOUND]: 'No internal swap route available for this token.',
        [RELAY_ERROR_CODES.NO_QUOTES]: 'Unable to get a quote. Try again or use a different token.',
        [RELAY_ERROR_CODES.ROUTE_TEMPORARILY_RESTRICTED]: 'This route is temporarily unavailable. Please try again later.',
        [RELAY_ERROR_CODES.SANCTIONED_CURRENCY]: 'This token is restricted and cannot be swapped.',
        [RELAY_ERROR_CODES.SANCTIONED_WALLET_ADDRESS]: 'This wallet address is restricted.',
        [RELAY_ERROR_CODES.SWAP_IMPACT_TOO_HIGH]: 'Price impact is too high. Try a smaller amount.',
        [RELAY_ERROR_CODES.UNSUPPORTED_CURRENCY]: 'This token is not supported for swapping.',
        [RELAY_ERROR_CODES.UNSUPPORTED_CHAIN]: 'This chain is not currently supported.',
        [RELAY_ERROR_CODES.UNSUPPORTED_EXECUTION_TYPE]: 'This execution type is not supported.',
        [RELAY_ERROR_CODES.UNSUPPORTED_ROUTE]: 'This swap route is not supported.',
        [RELAY_ERROR_CODES.UNAUTHORIZED]: 'Unauthorized request.',
        [RELAY_ERROR_CODES.USER_RECIPIENT_MISMATCH]: 'Recipient must match the connected wallet for this route.',
        [RELAY_ERROR_CODES.DESTINATION_TX_FAILED]: 'The transaction failed on the destination chain.',
        [RELAY_ERROR_CODES.ERC20_ROUTER_ADDRESS_NOT_FOUND]: 'Routing contract not found for this token.',
        [RELAY_ERROR_CODES.SWAP_QUOTE_FAILED]: 'Failed to calculate quote. Please try again.',
        [RELAY_ERROR_CODES.PERMIT_FAILED]: 'Permit signature failed. Please try again.',
        [RELAY_ERROR_CODES.INVALID_SLIPPAGE_TOLERANCE]: 'Invalid slippage value.',
    };
    return messages[errorCode] || fallbackMessage || 'An error occurred. Please try again.';
};
